config/routes.rb
StuffFinder::Application.routes.draw do
  devise_for :users
  get "categories/show"
  root "welcome#index"
  resources :classifieds
  resources :categories, only: :show
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :classifieds

  def recent_classifieds
    classifieds.limit(5).order('created_at DESC')
  end

  def self.from_params(category)
    where(name: category.capitalize).first_or_create
  end
end

app/models/classified.rb
class Classified < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :classifieds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find params[:id]
  end
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @categories = Category.order(:name)
  end

  def new
    @classified = Classified.new
    @categories = Category.pluck(:name)
  end

  def create
    safe_classified = params.require(:classified).permit(:title, :description, :price)
    @classified = current_user.classifieds.new safe_classified
    @classified.category = Category.from_params params[:category]
    @classified.save
    redirect_to @classified
  end

  def show
    @classified = Classified.find params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'
  before_action :redirect_if_logged_in
  def index
    @categories = Category.all
  end

  private

  def redirect_if_logged_in
    if user_signed_in?
      redirect_to classifieds_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/show.html.erb
<h1>Listings under <%= @category.name %></h1>
<section class="well">
  <ul class="unstyled">
    <% @category.classifieds.each do |classified| %>
      <li><%= link_to "#{truncate(classified.title)} - #{number_to_currency classified.price}", classified %></li>
    <% end %>
  </ul>
</section>

app/views/classifieds/index.html.erb
<section>
  <h2>Classifieds</h2>
  <% @categories.each do |category| %>
    <article>
      <section class="well well-small">
        <ul class="nav nav-list">
          <li class="nav-header"><%= link_to category.name, category %></li>
          <header>
            <% category.recent_classifieds.each do |classified| %>
            </header>
            <article>
              <li><%= link_to "#{truncate(classified.title)} - #{number_to_currency classified.price}", classified %></li>
            </article>
          <% end %>
        </ul>
      </section>
    </article>
  <% end %>
</section>
<%= content_for(:sidebar) do %>
  <section class="well">
    <ul class="nav nav-list">
      <li class="nav-header">Categories</li>
    <% @categories.each do |category| %>
      <li><%= link_to category.name, category %></li>
    <% end %>
  </ul>
<% end %> 

app/views/classifieds/new.html.erb
<h1>Add a classified</h1>
<%= form_for @classified do |f| %>
  <fieldset>
    <%= label_tag :category %>
    <%= text_field_tag :category, "",  data: {provide: "typeahead", source: @categories}, required: true, autocomplete: "off"%>
    <%= f.label :title %>
    <%= f.text_field :title, required: true%>
    <%= f.label :description %>
    <%= f.text_area :description, required: true%>
    <%= f.label :price %>
    <span class="add-on">$</span>
    <%= f.number_field :price, :size => 5, :value => 0, :step => 1, :min => 0 %>
    <span class="add-on">.00</span>
  </fieldset>
  <%= f.submit class: "btn btn-success btn-large" %>
  <%= link_to "Back", :back,  class: "btn btn-danger btn-large" %>
<% end %>

app/views/classifieds/show.html.erb
<h1><%= @classified.title %> - <%= number_to_currency @classified.price %></h1>
<section class="well well-small">
  <p>Contact this seller <%= mail_to @classified.user.email, "here", subject: "StuffFinder - #{@classified.title}" %></p>
  <div>
    <p class="lead"><%= @classified.description %></p>
  </div>
</section>
More from <%= link_to @classified.category.name, @classified.category %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StuffFinder</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= link_to "Stuff Finder", root_path %>
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>

  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StuffFinder" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "StuffFinder", root_path, class: "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Classifieds", classifieds_path  %></li>
              <li><%= link_to "New Classified", new_classified_path  %></li>
              <% if user_signed_in? %>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; RubyBubble</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/welcome/index.html.erb
<section class="hero-unit">
  <h1>Your place for finding stuff you want, and dumping stuff you don't</h1>

  <div class='action-buttons'>
    <%= link_to "Create a new classified!", new_classified_path, class: 'btn btn-success btn-large' %>
    <%= link_to "See our current classifieds", classifieds_path, class: 'btn btn-primary btn-large' %>
  </div>
</section>